### ISSUE TITLE
Problem with entity type cover

### ISSUE THREAD

**Issue by xlemassacre** [BimmerGestalt/HassGestalt#13]
Hey,

I've tried to use the app to control my garage door.
The entity from my dashboard is shown in the car, but I can't open/close it. Nothing is happening when I press it.

**Comment by hufman** [comment]
The `cover` domain is [not configured](https://github.com/BimmerGestalt/HassGestalt/blob/7b05cd4d938309ddbfc487381fa8658bee2649dc/app/src/main/java/io/bimmergestalt/hassgestalt/hass/EntityController.kt#L11) to support a command. I read now that `cover` [supports the generic toggle command](https://www.home-assistant.io/integrations/cover/#cover-control-services), would that work for your environment?

**Comment by xlemassacre** [comment]
Yes toggle would be perfect, just tested it via home assisant services (opens the garagedoor when it's closed and also the other way around)

**Comment by hufman** [comment]
This should be rolling out to the app store soon, or you can grab the APK directly from the Releases page.

**Comment by xlemassacre** [comment]
Wow thanks for that quick fix! Already got the update and could now sucessfully open/close my garage door from the car.

**Comment by hufman** [comment]
You're welcome! This was an easy thing to fix, the other thing you wanted won't be so fast, sorry!

**Comment by xlemassacre** [comment]
No worries, thought so that the other thing is more complex.
