### ISSUE TITLE
Crash when clicking login [logcat]

### ISSUE THREAD

**Issue by CJOS100** [BimmerGestalt/HassGestalt#6]
Hi Walter,

The application crashes when I enter my HASS domain and click login, I have attached a full logcat: [logcat_hassgestalt_crash.log](https://github.com/BimmerGestalt/HassGestalt/files/8550630/logcat_hassgestalt_crash.log)

I think the issue is: `java.lang.IllegalArgumentException: io.bimmergestalt.hassgestalt: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.`

Device: Galaxy Note 20
Device Version: Android 12
App Version: Latest release as of posting, 100021 (0.1-20-b919795-loading_spinner)

Thanks for working on this application :grin:

**Comment by hufman** [comment]
Thank you for the clear information and bug report! It should be fixed in the latest main build.
