### ISSUE TITLE
App doesn't show any entities in the phoneui or in the car.

### ISSUE THREAD

**Issue by rahgun04** [BimmerGestalt/HassGestalt#8]
App doesn't show any entities in the phoneui or in the car although the demo server does work.
Home assistant webpage shows that an api refresh token was handed out to the app.
All 3 required endpoints are visible

**Comment by hufman** [comment]
The app only shows entities grouped into dashboards, do you have any custom Lovelace dashboards configured?

**Comment by rahgun04** [comment]
Thanks, Got it to work now
